monitor/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
import views

urlpatterns = patterns(
  '',
  url(r'^$', views.index),

  url(r'^metrics/', views.show_all_metrics),
  url(r'^metrics_config/', views.show_all_metrics_config),

  url(r'^counters/', views.show_all_counters),
  url(r'^addCounter/$', views.add_counter),


  url(r'^service/(?P<id>\d+)/$', views.show_service),
  url(r'^cluster/(?P<id>\d+)/$', views.show_cluster),
  url(r'^cluster/(?P<id>\d+)/task/$', views.show_cluster_task_board),
  url(r'^cluster/(?P<id>\d+)/basic/$', views.show_cluster_basic_board),
  url(r'^cluster/(?P<id>\d+)/table/$', views.show_cluster_table_board),
  url(r'^cluster/(?P<id>\d+)/regionserver/$', views.show_cluster_regionserver_board),
  url(r'^cluster/(?P<id>\d+)/replication/$', views.show_cluster_replication),

  url(r'^job/(?P<id>[^/]+)/$', views.show_job),
  url(r'^task/(?P<id>[^/]+)/$', views.show_task),


  url(r'^table/(?P<id>\d+)/$', views.show_table),
  url(r'^table/operation/(?P<id>\d+)/$', views.show_table_operation),
  url(r'^cluster/operation/(?P<id>\d+)/$', views.show_cluster_operation),
  url(r'^cluster/operation/tablecomparsion/(?P<id>\d+)/$', views.show_cluster_operation_table_comparison),
  url(r'^regionserver/(?P<id>\d+)/$', views.show_regionserver),
  url(r'^regionserver/operation/(?P<id>\d+)/$', views.show_regionserver_operation),
)

owl/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import RedirectView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns(
  '',
  # Examples:
  url(r'^$', RedirectView.as_view(url='/monitor/')),
  # url(r'^owl/', include('owl.foo.urls')),

  # Uncomment the admin/doc line below to enable admin documentation:
  url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

  # Uncomment the next line to enable the admin:
  url(r'^admin/', include(admin.site.urls)),

  url(r'^accounts/', include('django.contrib.auth.urls')),

  url(r'^monitor/', include('monitor.urls')),
)

monitor/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils import timezone

import datetime
import json


DEFAULT_DATETIME = datetime.datetime(1970, 1, 1, tzinfo=timezone.utc)
# If a cluster/job/task's last success time has passed this many seconds, it's
# considered as fialed.
FAIL_TIME = 60

# The item could be cluster, job, or task.
def is_healthy(item, fail_time=FAIL_TIME):
  delta = datetime.timedelta(seconds=fail_time)
  if item.last_success_time + delta < datetime.datetime.now(tz=timezone.utc):
    return False
  return True


class Status:
  OK = 0
  WARN = 1
  ERROR = 2


class Service(models.Model):
  # Name of the service, like "hdfs", "hbase", etc.
  name = models.CharField(max_length=128)
  # Url to get metrics which is formatted in json.
  metric_url = models.CharField(max_length=128)
  # If the service is being actively monitored. We don't want to delete metrics
  # data once a service/cluster/job is deactive, so just use a boolean field to
  # indicate it.
  active = models.BooleanField(default=True)
  # A text description.
  description = models.CharField(max_length=1024)

  def __unicode__(self):
    return self.name


class Cluster(models.Model):
  # Each cluster must belong to one service.
  service = models.ForeignKey(Service, db_index=True)
  # The cluster name like "ggsrv-miliao", "sdtst-test", etc.
  name = models.CharField(max_length=128)
  # The same as service.
  active = models.BooleanField(default=True)
  # A text description.
  description = models.CharField(max_length=1024)
  # The last attempt time to fetch metics, whether successful or failed.
  # It's the time of client initiating the request, not the time of client
  # receiving the response.
  last_attempt_time = models.DateTimeField(default=DEFAULT_DATETIME)
  # If the last attempt is successful.
  last_status = models.IntegerField(default=Status.ERROR)
  # The status mesage of last attempt.
  last_message = models.CharField(max_length=128)
  # The last update time of this task's metics, must be successful.
  # The definition is the same as last_attempt.
  last_success_time = models.DateTimeField(default=DEFAULT_DATETIME)
  # cluster version in format: "version, revision"
  version = models.CharField(max_length=128)
  # Entry for service's native main page
  entry = models.CharField(max_length=128)

  @property
  def health(self):
    return is_healthy(self)

  def __unicode__(self):
    return u"%s/%s" % (unicode(self.service), self.name)


class Job(models.Model):
  # Each job must belong to one cluster.
  cluster = models.ForeignKey(Cluster, db_index=True)
  # The job name like "namenode", "regionserver", etc.
  name = models.CharField(max_length=128)
  # The same as service.
  active = models.BooleanField(default=True)
  # A text description.
  description = models.CharField(max_length=1024)
  # How many tasks are in running and healthy.
  running_tasks_count = models.IntegerField(default=0)
  # How many tasks in total.
  total_tasks_count = models.IntegerField(default=0)
  # The last attempt time to fetch metics, whether successful or failed.
  # It's the time of client initiating the request, not the time of client
  # receiving the response.
  last_attempt_time = models.DateTimeField(default=DEFAULT_DATETIME)
  # If the last attempt is successful.
  last_status = models.IntegerField(default=Status.ERROR)
  # The status mesage of last attempt.
  last_message = models.CharField(max_length=128)
  # The last update time of this task's metics, must be successful.
  # The definition is the same as last_attempt.
  last_success_time = models.DateTimeField(default=DEFAULT_DATETIME)

  @property
  def health(self):
    return is_healthy(self)

  def __unicode__(self):
    return u"%s/%s" % (unicode(self.cluster), self.name)


class Task(models.Model):
  job = models.ForeignKey(Job, db_index=True)
  # The task id.
  task_id = models.IntegerField()
  # The ip or hostname that the task is running on.
  host = models.CharField(max_length=128)
  # The port number where we could get metrics data from.
  port = models.IntegerField()
  # The same as service.
  active = models.BooleanField(default=True)
  # The last attempt time to fetch metics, whether successful or failed.
  # It's the time of client initiating the request, not the time of client
  # receiving the response.
  last_attempt_time = models.DateTimeField(default=DEFAULT_DATETIME)
  # If the last attempt is successful.
  last_status = models.IntegerField(default=Status.ERROR)
  # The status mesage of last attempt.
  last_message = models.CharField(max_length=128)
  # The last update time of this task's metics, must be successful.
  # The definition is the same as last_attempt.
  last_success_time = models.DateTimeField(default=DEFAULT_DATETIME)
  # The last metric values, encoded in json.
  last_metrics = models.TextField()
  # The last raw metric values fetched from http server, for debug purpose
  last_metrics_raw = models.TextField()

  class Meta:
    unique_together = [["host", "port"],]

  @property
  def health(self):
    return is_healthy(self)

  def __unicode__(self):
    return u"%s/%d" % (unicode(self.job), self.task_id)

class HBaseCluster(models.Model):
  cluster = models.OneToOneField(Cluster, db_index=True)

  memStoreSizeMB = models.IntegerField(default = 0)
  storefileSizeMB = models.IntegerField(default = 0)
  # readRequestsCount and writeRequestsCount may exceed max integer
  readRequestsCount = models.FloatField(default = 0, max_length = 20)
  writeRequestsCount = models.FloatField(default = 0, max_length = 20)
  readRequestsCountPerSec = models.IntegerField(default = 0)
  writeRequestsCountPerSec = models.IntegerField(default = 0)
  operationMetrics = models.TextField() # save operation metrics as json format

class RegionServer(models.Model):
  cluster = models.ForeignKey(Cluster, db_index=True)
  task = models.OneToOneField(Task, db_index=True)
  name = models.CharField(max_length=128)
  last_attempt_time = models.DateTimeField(default=DEFAULT_DATETIME)
  load = models.IntegerField(default = 0)
  numberOfRegions = models.IntegerField(default = 0)
  numberOfRequests = models.IntegerField(default = 0)

  memStoreSizeMB = models.IntegerField(default = 0)
  storefileSizeMB = models.IntegerField(default = 0)
  readRequestsCount = models.IntegerField(default = 0)
  writeRequestsCount = models.IntegerField(default = 0)
  readRequestsCountPerSec = models.IntegerField(default = 0)
  writeRequestsCountPerSec = models.IntegerField(default = 0)
  replication_last_attempt_time = models.DateTimeField(default=DEFAULT_DATETIME)
  replicationMetrics = models.TextField() # save replication metrics as json format

  def __unicode__(self):
    return unicode(self.name.split(',')[0])

class Table(models.Model):
  cluster = models.ForeignKey(Cluster, db_index=True)
  name = models.CharField(max_length=128)
  last_attempt_time = models.DateTimeField(default=DEFAULT_DATETIME)

  memStoreSizeMB = models.IntegerField(default = 0)
  storefileSizeMB = models.IntegerField(default = 0)
  readRequestsCount = models.IntegerField(default = 0)
  writeRequestsCount = models.IntegerField(default = 0)
  readRequestsCountPerSec = models.IntegerField(default = 0)
  writeRequestsCountPerSec = models.IntegerField(default = 0)

  availability = models.FloatField(default=-1.0)
  operationMetrics = models.TextField() # save operation metrics as json format

  def __unicode__(self):
    return unicode(self.name)

ROOT_TABLE_NAME = '-ROOT-'
META_TABLE_NAME = '.META.'
ROOT_REGION_ENCODING_NAME = '70236052'
META_REGION_ENCODING_NAME = '1028785192'

class Region(models.Model):
  table = models.ForeignKey(Table, db_index=True)
  region_server = models.ForeignKey(RegionServer, db_index=True)
  last_attempt_time = models.DateTimeField(default=DEFAULT_DATETIME)
  name = models.CharField(max_length=256)
  encodeName = models.CharField(max_length = 128, db_index=True)

  memStoreSizeMB = models.IntegerField(default = 0)
  storefileSizeMB = models.IntegerField(default = 0)
  readRequestsCount = models.IntegerField(default = 0)
  writeRequestsCount = models.IntegerField(default = 0)
  readRequestsCountPerSec = models.IntegerField(default = 0)
  writeRequestsCountPerSec = models.IntegerField(default = 0)

  currentCompactedKVs = models.IntegerField(default = 0)
  requestsCount = models.IntegerField(default = 0)
  rootIndexSizeKB = models.IntegerField(default = 0)
  storefileIndexSizeMB = models.IntegerField(default = 0)
  storefiles = models.IntegerField(default = 0)
  stores = models.IntegerField(default = 0)
  totalCompactingKVs = models.IntegerField(default = 0)
  totalStaticBloomSizeKB = models.IntegerField(default = 0)
  totalStaticIndexSizeKB = models.IntegerField(default = 0)
  version = models.IntegerField(default = 0)
  last_operation_attempt_time = models.DateTimeField(default=DEFAULT_DATETIME)
  operationMetrics = models.TextField() # save operation metrics as json format

  # root and meta region use old region format, where root regon name is: '-ROOT-,,0.70236052'
  # and first meta region name is: .META.,,1.1028785192. 70236052 and 1028785192 will serve as
  # encode name for root region and meta region respectively. Other data region use new format,
  # such as hbase_client_test_table,01,1369368306964.7be6b8bda3e59d5e6d4556482fc84601. in which
  # 7be6b8bda3e59d5e6d4556482fc84601 will serve as encode name
  @staticmethod
  def get_encode_name(name):
    if name[0:6] == ROOT_TABLE_NAME:
      return ROOT_REGION_ENCODING_NAME
    if name[0:6] == META_TABLE_NAME:
      return META_REGION_ENCODING_NAME
    return name.split('.')[1]

  # the region operation metric name(AvgTime) for 'multiput' seems like:
  # tbl.hbase_client_test_table.region.9fdec6d4dbb175e2b098e16fc5987dcb.multiput_AvgTime where
  # 9fdec6d4dbb175e2b098e16fc5987dcb is the encode name
  @staticmethod
  def is_region_operation_metric_name(name):
    if name.find('tbl') >= 0 and name.find('region') >= 0:

templates/monitor/chart_config.html
{% extends "base.html" %}

{% block content %}
    <h2> All chart config. </h2>
    <a href="/admin/monitor/chartconfig/add/">Add a chart config</a>
    <a href="/admin/monitor/chartconfig/">Change chart configs</a>
    <table class="table table-striped table-bordered">
        <thead>
        <tr>
            <th>group name</th>
            <th>chart name</th>
            <th>metrics</th>
            <th>type</th>
        </tr>
        </thead>
        <tbody>
        {% for config in configs %}
            <tr>
                <td>{{ config.group_name }}</td>
                <td>{{ config.chart_name }}</td>
                <td>{{ config.metrics }}</td>
                <td>{{ config.type }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/monitor/cluster.html
{% extends "base.html" %}

{% block content %}
    <ul class="breadcrumb">
        <li>
            <a href="/monitor/service/{{ cluster.service.id }}">{{ cluster.service.name }}</a> <span
                class="divider">/</span>
        </li>
        <li class="active">{{ cluster.name }}</li>
    </ul>
    <h2> All Tasks. </h2>
    <table class="table table-striped table-bordered">
        <thead>
        <tr>
            <th>job</th>
            <th>task id</th>
            <th>task entry</th>
            <th>last success</th>
        </tr>
        </thead>
        <tbody>
        {% for task in tasks %}
            <tr>
                <td><a href="/monitor/job/{{ task.job.id }}">{{ task.job.name }}</a></td>
                <td><a href="/monitor/task/{{ task.id }}">{{ task.task_id }}</a></td>
                <td><a href="http://{{ task.host }}:{{ task.port }}/">{{ task.host }}:{{ task.port }}</a></td>
                <td>{{ task.last_success_time }}
                    {% if task.health %}
                        <img src="{{ STATIC_URL }}/ok.png" width="24" alt="Big Boat"/>
                    {% else %}
                        <img src="{{ STATIC_URL }}/alert.png" width="24" alt="Big Boat"/>
                    {% endif %}
                </td>

            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/monitor/hbase_cluster_operation.html
{% extends "monitor/hbase_base.html" %}
{% load extended_filter %}

{% block hbase_content %}
    <div class="row">
        <div id="sidebar" class="span1">
            <ul class="nav nav-list affix">
                <li><a href="/monitor/cluster/{{cluster.id}}/basic">SummaryMetrics</a></li>
                <li><a href="/monitor/cluster/operation/tablecomparsion/{{cluster.id}}">Comparsion</a></li>
                <li><strong>---------------</strong></li>
                {% for metric in tsdb_metrics %}
                <li><a href="#{{metric.0}}">{{metric.0}}</a></li>
                {% endfor %}
            </ul>
        </div>
        <div class="span11">
        {% for metric in tsdb_metrics %}
        <section id="{{metric.0}}">
        <div class="row">
            <div class="span5">
                <center>{{metric.1.title}}</center>
                <a href="{{tsdb_url_prefix}}/#start={{start_date}}{{metric.1.query}}&yrange=[0:]&key=out%20center%20top&wxh=1000x400" >
                    <img src="{{tsdb_url_prefix}}/q?start={{start_date}}{{ metric.1.query}}&yrange=[0:]&key=out%20center%20top&wxh={{5|pic_width}}x{{metric.1.query|pic_heigth}}&png" />
                </a>
            </div>
            <div class="span5">
                <center>{{metric.2.title}}</center>
                <a href="{{tsdb_url_prefix}}/#start={{start_date}}{{metric.2.query}}&yrange=[0:]&key=out%20center%20top&wxh=1000x400" >
                    <img src="{{tsdb_url_prefix}}/q?start={{start_date}}{{metric.2.query}}&yrange=[0:]&key=out%20center%20top&wxh={{5|pic_width}}x{{metric.2.query|pic_heigth}}&png" />
                </a>
            </div>
        </div>
        </section>
        {% endfor %}
        </div>
    </div>
{% endblock %}

templates/monitor/hbase_cluster_operation_table_comparsion.html
{% extends "monitor/hbase_base.html" %}
{% load extended_filter %}

{% block hbase_content %}
    <div class="row">
        <div id="sidebar" class="span1">
            <ul class="nav nav-list affix">
                <li><a href="/monitor/cluster/{{cluster.id}}/basic">SummaryMetrics</a></li>
                <li><a href="/monitor/cluster/operation/{{cluster.id}}">Overall</a></li>
                <li><strong>---------------</strong></li>
                {% for operation, metrics in tsdb_metrics.iteritems%}
                <li><a href="#{{operation}}">{{operation}}</a></li>
                {% endfor %}
            </ul>
        </div>
        <div class="span11">
        {% for operation, metrics in tsdb_metrics.iteritems %}
        <section id="{{operation}}">
        <div class="row">
            <div class="span5">
                <center>{{metrics.0.title}}</center>
                <a href="{{tsdb_url_prefix}}/#start={{start_date}}{{metrics.0.query|join:""}}&yrange=[0:]&key=out%20center%20top&wxh=1000x400" >
                    <img src="{{tsdb_url_prefix}}/q?start={{start_date}}{{ metrics.0.query|join:""}}&yrange=[0:]&key=out%20center%20top&wxh={{5|pic_width}}x{{metrics.0.query|pic_heigth}}&png" />
                </a>
            </div>
            <div class="span5">
                <center>{{metrics.1.title}}</center>
                <a href="{{tsdb_url_prefix}}/#start={{start_date}}{{metrics.1.query|join:""}}&yrange=[0:]&key=out%20center%20top&wxh=1000x400" >
                    <img src="{{tsdb_url_prefix}}/q?start={{start_date}}{{metrics.1.query|join:""}}&yrange=[0:]&key=out%20center%20top&wxh={{5|pic_width}}x{{metrics.1.query|pic_heigth}}&png" />
                </a>
            </div>
        </div>
        </section>
        {% endfor %}
        </div>
    </div>
{% endblock %}

templates/monitor/hbase_regionserver_board.html
{% extends "monitor/hbase_base.html" %}

{% block hbase_content %}
    <div class="row">
        <div class="span12">
            <h3>QPS distribution on region servers</h3>
        </div>
    </div>
    <div class="row">
        <div class="span6"> {{ read_requests_dist_by_rs_chart }} </div>
        <div class="span6"> {{ write_requests_dist_by_rs_chart }} </div>
    </div>
    <div class="row">
        <div class="span12"> 
            <h3>Region Server</h3>
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>region server</th>
                        <th>memstore size(MB)</th>
                        <th>storefile size(MB)</th>
                        <th>read qps</th>
                        <th>write qps</th>
                    </tr>
                </thead>
                <tbody>
                    {% for regionserver in regionservers %}
                    <tr>
                        <td><a href="/monitor/regionserver/{{ regionserver.id }}">{{ regionserver.name }}</a></td>
                        <td>{{ regionserver.memStoreSizeMB }}</td>
                        <td>{{ regionserver.storefileSizeMB }}</td>
                        <td>{{ regionserver.readRequestsCountPerSec }}</td>
                        <td>{{ regionserver.writeRequestsCountPerSec }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/monitor/hbase_regionserver_operation.html
{% extends "monitor/hbase_base.html" %}
{% load extended_filter %}

{% block hbase_content %}
    <div class="row">
        <div id="sidebar" class="span1">
            <ul class="nav nav-list affix">
                <li><a href="/monitor/regionserver/{{regionserver.id}}">SummaryMetrics</a></li>
                <li><strong>---------------</strong></li>
                {% for metric in tsdb_metrics%}
                <li><a href="#{{metric.0}}">{{metric.0}}</a></li>
                {% endfor %}
            </ul>
        </div>
        <div class="span11">
        {% for metric in tsdb_metrics %}
        <section id="{{metric.0}}">
            <div class="row">
                <div class="span11">
                  <!-- show NumOps -->
                  <div class="span5">
                    <center>{{metric.1.title}}</center>
                    <a href="{{tsdb_url_prefix}}/#start={{start_date}}{{ metric.1.query }}&yrange=[0:]&key=out%20center%20top&wxh=1000x400" >
                    <img src="{{tsdb_url_prefix}}/q?start={{start_date}}{{ metric.1.query}}&yrange=[0:]&key=out%20center%20top&wxh={{5|pic_width}}x{{tsdb_read_query|pic_heigth}}&png" />
                    </a>
                  </div>

                  <!-- show percentile graph if necessary -->
                  <div class="span5">
                    <center>{{metric.2.title}}</center>
                    <a href="{{tsdb_url_prefix}}/#start={{start_date}}{{metric.2.query}}&yrange=[0:]&key=out%20center%20top&wxh=1000x400" >
                    <img src="{{tsdb_url_prefix}}/q?start={{start_date}}{{metric.2.query}}&yrange=[0:]&key=out%20center%20top&wxh={{5|pic_width}}x{{tsdb_write_query|pic_heigth}}&png" />
                </a>
                  </div>
            </div>
        </section>
        {% endfor %}
        </div>
    </div>
{% endblock %}

templates/monitor/hbase_service.html
{% extends "base.html" %}
{% load extended_filter %}

{% block content %}
  <h2> All clusters for {{ service.name }}. </h2>
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>name</th>
        <th>job (running/total tasks)</th>
        <th>cluster entry</th>
        <th>version</th>
        <th>description</th>
      </tr>
    </thead>
    <tbody>
      {% for cluster in clusters %}
        <tr>
          <td>
            {% if cluster.health %}
              {% if cluster.last_status == 0 %}
                <img src="{{ STATIC_URL }}/ok.png" width="24" alt="Big Boat"/>
              {% elif cluster.last_status == 1 %}
                <img src="{{ STATIC_URL }}/warn.png" width="24" alt="Big Boat"/>
              {% endif %}
            {% else %}
              <img src="{{ STATIC_URL }}/alert.png" width="24" alt="Big Boat"/>
            {% endif %}
            <a href="/monitor/service/{{ cluster.service.id }}/">{{ cluster.service.name }}</a> / 
            <a href="/monitor/cluster/{{ cluster.id }}/">{{ cluster.name }}</a>
          </td>
          <td>
            {% for job in cluster.job_set.all %}
              {% if job.health %}
                {% if job.last_status == 0 %}
                  <img src="{{ STATIC_URL }}/ok.png" width="24" alt="Big Boat"/>
                {% elif job.last_status == 1 %}
                  <img src="{{ STATIC_URL }}/warn.png" width="24" alt="Big Boat"/>
                {% endif %}
              {% else %}
                <img src="{{ STATIC_URL }}/alert.png" width="24" alt="Big Boat"/>
              {% endif %}
              {{ job.name }} ({{ job.running_tasks_count }}/{{ job.total_tasks_count }})
              <font color="red">{{ job.last_message }}</font>
              <br>
            {% endfor %}
          </td>
          <td>
            <a href="http://{{cluster.entry}}">{{cluster.entry}}</a>
          </td>
          <td>{{ cluster.version }}</td>
          <td>{{ cluster.description }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <h3>QPS Comparison</h3>
  <div class="row">
      <div class = "span6">
          <a href="{{tsdb_url_prefix}}/#start={{start_date}}{{ tsdb_read_query|join:""}}&yrange=[0:]&key=out%20center%20top&wxh=1000x400" >
              <img src="{{tsdb_url_prefix}}/q?start={{start_date}}{{ tsdb_read_query|join:""}}&yrange=[0:]&key=out%20center%20top&wxh={{6|pic_width}}x{{tsdb_read_query|pic_heigth}}&png" />
          </a>
      </div>
      <div class = "span6">
          <a href="{{tsdb_url_prefix}}/#start={{start_date}}{{ tsdb_write_query|join:""}}&yrange=[0:]&key=out%20center%20top&wxh=1000x400" >
              <img src="{{tsdb_url_prefix}}/q?start={{start_date}}{{ tsdb_write_query|join:""}}&yrange=[0:]&key=out%20center%20top&wxh={{6|pic_width}}x{{tsdb_write_query|pic_heigth}}&png" />
          </a>
      </div>
  </div>
{% endblock %}

templates/monitor/hbase_table_operation.html
{% extends "monitor/hbase_base.html" %}
{% load extended_filter %}

{% block hbase_content %}
    <div class="row">
        <div id="sidebar" class="span1">
            <ul class="nav nav-list affix">
                <li><a href="/monitor/table/{{table.id}}">SummaryMetrics</a></li>
                <li><strong>---------------</strong></li>
                {% for metric in tsdb_metrics %}
                <li><a href="#{{metric.0}}">{{metric.0}}</a></li>
                {% endfor %}
            </ul>
        </div>
        <div class="span11">
        {% for metric in tsdb_metrics %}
        <section id="{{metric.0}}">
        <div class="row">
            <div class="span5">
                <center>{{metric.1.title}}</center>
                <a href="{{tsdb_url_prefix}}/#start={{start_date}}{{ metric.1.query }}&yrange=[0:]&key=out%20center%20top&wxh=1000x400" >
                    <img src="{{tsdb_url_prefix}}/q?start={{start_date}}{{ metric.1.query}}&yrange=[0:]&key=out%20center%20top&wxh={{5|pic_width}}x{{tsdb_read_query|pic_heigth}}&png" />
                </a>
            </div>
            <div class="span5">
                <center>{{metric.2.title}}</center>
                <a href="{{tsdb_url_prefix}}/#start={{start_date}}{{metric.2.query}}&yrange=[0:]&key=out%20center%20top&wxh=1000x400" >
                    <img src="{{tsdb_url_prefix}}/q?start={{start_date}}{{metric.2.query}}&yrange=[0:]&key=out%20center%20top&wxh={{5|pic_width}}x{{tsdb_write_query|pic_heigth}}&png" />
                </a>
            </div>
        </div>
        </section>
        {% endfor %}
        </div>
    </div>
{% endblock %}

templates/monitor/hdfs_task_board.html
{% extends "base.html" %}

{% block content %}
    <ul class="breadcrumb">
        <li>
            <a href="/monitor/service/{{ cluster.service.id }}">{{ cluster.service.name }}</a> <span
                class="divider">/</span>
        </li>
        <li class="active">{{ cluster.name }}</li>
    </ul>
    <ul class="nav nav-pills">
        <li class="active">
        <a href="/monitor/cluster/{{ cluster.id }}/task/">Tasks</a>
        </li>
    </ul>
    <table class="table table-striped table-bordered">
        <thead>
        <tr>
            <th>job</th>
            <th>task id</th>
            <th>task entry</th>
            <th>last success</th>
        </tr>
        </thead>
        <tbody>
        {% for task in tasks %}
            <tr>
                <td>
                    {% if task.job.name == "datanode" %}
                        <a href="/monitor/task/{{ task.id }}">{{ task.job.name }}</a>
                    {% else %}
                        <a href="/monitor/job/{{ task.job.id }}">{{ task.job.name }}</a>
                    {% endif %}
                </td>
                <td><a href="/monitor/task/{{ task.id }}">{{ task.task_id }}</a></td>
                <td><a href="http://{{ task.host }}:{{ task.port }}/">{{ task.host }}:{{ task.port }}</a></td>
                <td>{{ task.last_success_time }}
                    {% if task.health %}
                        <img src="{{ STATIC_URL }}/ok.png" width="24" alt="Big Boat"/>
                    {% else %}
                        <img src="{{ STATIC_URL }}/alert.png" width="24" alt="Big Boat"/>
                    {% endif %}
                </td>

            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/monitor/test.html
{% extends "base.html" %}

{% block content %}
    {{ test }}
{% endblock %}